version: '3.8'
services:

    # Application
    app:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        container_name: quickpay-application
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - "database"
        environment:
            UPLOAD_LIMIT: 65M

    # Web Server
    web:
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        container_name: quickpay-nginx
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - "8010:80"

    # Database
    database:
        image: mysql:8.0
        container_name: quickpay-mysql
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "33061:3306"

    # Database management
    pma:
        image: phpmyadmin:5.1
        container_name: quickpay-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
        depends_on:
            - database
        ports:
            - "8888:80"

volumes:
    dbdata:
    elasticsearch:
      driver: local
